### ISSUE TITLE
Add section for ceph-metrics

### ISSUE THREAD

**Issue by mulbc** [red-hat-storage/ocs-training#104]
**Do you need more detailed steps on an existing section? Please describe.**
Add a section on how to set up ceph-metrics with a dedicated Grafana instance.

**Comment by jeanchlopez** [comment]
Do you mean that we want a section to illustrate what we can do today or what we should have in here with the Nautilus dashboards integrated or how to provide a workaround to the fact that we have nothing as of today when it comes down to Ceph metrics?

**Comment by netzzer** [comment]
One idea is to have new content on using OCP4 Prometheus metrics to create graphs that can be used for troubleshooting the cluster and/or understanding used capacity of the cluster, used and available.

**Comment by mulbc** [comment]
Yes, so basically a short intro to how people could get the dashboards they may have used with RHCS & ceph-metrics in Openshift with OCS.

I might base this on https://github.com/cloud-bulldozer/dittybopper since there are recommendations to not use the built-in Grafana instance

**Comment by jeanchlopez** [comment]
That's exactly my fear. Demonstrates and somehow recommend implicitly a kludge rather than having an official integration.

If that's OK with you, until we decide if dittybopper is the line to go for Grafana until hopefully we have an official integration of the Grafana ceph dashboards, I'd rather start creating content on how to use the Prometheus metrics we collect. And then as an optional item, do the this.

I'll get started onit this way.

**Comment by mulbc** [comment]
Discussed this with JC and we concluded that he will write a section on what is possible using the tools that are provided (and properly supported) with OCS using the "Graph" feature of the Prometheus Web UI (inside the Openshift Web UI)

Then we will have an additional section that is marked as additional off-course work that explains how one could theoretically spin up a new Grafana instance to get the ceph-metrics dashboards running. I can write this part if necessary and update the ceph-metrics dashboards to work with OCS.
